import Head from "next/head";
import Script from "next/script";

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>CopeAi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
                    rel="stylesheet"
                />
                <link rel="stylesheet" href="/css/plugins.css" />
                <link rel="stylesheet" href="/styles/common_style.css" />
                <link rel="stylesheet" href="/assets/css/home7-style.css" />
            </Head>

            <div>
                <main>{children}</main>
            </div>
        </>
    );
}
